In [2]:
from e2eml.classification import classification_blueprints

[nltk_data] Downloading package punkt to /home/thomas/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/thomas/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/thomas/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/thomas/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [3]:
sql_dataset = pd.read_csv("Corona_NLP_train.csv", encoding='latin-1')

In [5]:
len(sql_dataset.index)

41157

In [6]:
try:
    del sql_dataset["Unnamed: 0"]
except Exception:
    pass

sql_dataset = sql_dataset.copy()

In [7]:
sql_dataset.isna().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [8]:
train_df = sql_dataset.head(30000).copy()
train_df.to_csv("twitter_comment_raw_train.csv", index=False)
holdout_df = sql_dataset.tail(11000).copy()
holdout_df.to_csv("twitter_comment_raw_holdout.csv", index=False)
#holdout_df = train_df.loc[~((train_df["merchant_id"].isin(holdout_df_sample["merchant_id"]))), :].copy()
holdout_target = holdout_df["Sentiment"].copy()
del holdout_df["Sentiment"]
del sql_dataset
_ = gc.collect()

In [9]:
train_df["Sentiment"].value_counts()

Positive              8257
Negative              7382
Neutral               5482
Extremely Positive    4707
Extremely Negative    4172
Name: Sentiment, dtype: int64

In [10]:
holdout_target.value_counts()

Positive              3124
Negative              2493
Neutral               2200
Extremely Positive    1888
Extremely Negative    1295
Name: Sentiment, dtype: int64

In [11]:
train_df.head(5)

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/iFz9FAn2Pa and https://t.co/xX6ghGFzCC and https://t.co/I2NlzdxNo8,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to exchange phone numbers create contact list with phone numbers of neighbours schools employer chemist GP set up online shopping accounts if poss adequate supplies of regular meds but not over order,Positive
2,3801,48753,Vagabonds,16-03-2020,"Coronavirus Australia: Woolworths to give elderly, disabled dedicated shopping hours amid COVID-19 outbreak https://t.co/bInCA9Vp8P",Positive
3,3802,48754,NaN,16-03-2020,"My food stock is not the only one which is empty...\r\r\n\r\r\nPLEASE, don't panic, THERE WILL BE ENOUGH FOOD FOR EVERYONE if you do not take more than you need. \r\r\nStay calm, stay safe.\r\r\n\r\r\n#COVID19france #COVID_19 #COVID19 #coronavirus #confinement #Confinementotal #ConfinementGeneral https://t.co/zrlG0Z520j",Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COVID19 outbreak.\r\r\n\r\r\nNot because I'm paranoid, but because my food stock is litteraly empty. The #coronavirus is a serious thing, but please, don't panic. It causes shortage...\r\r\n\r\r\n#CoronavirusFrance #restezchezvous #StayAtHome #confinement https://t.co/usmuaLq72n",Extremely Negative

In [12]:
holdout_df.head(5)

,UserName,ScreenName,Location,TweetAt,OriginalTweet
30157,33956,78908,"Houston, TX",06-04-2020,"Financial markets have not been immune to the #coronavirus fallout, as panic-driven selling along with the uncertainty of our new economic reality combined to send asset prices sharply lower during the first quarter: https://t.co/SeOHvVZzKr\r\r\n\r\r\n#Markets #Investing"
30158,33957,78909,NaN,06-04-2020,The government need to force Argos to close Do they sell food Medicine So why is rhe queue 10x that of the supermarket
30159,33958,78910,NaN,06-04-2020,"3D model of the spread of coronavirus when a person coughs in a supermarket, created by the Aalto University. #Corona #Covid_19 #COVID19 https://t.co/HOzLTAJM1E"
30160,33959,78911,"Washington, DC Metro",06-04-2020,"Your #coronavirus #groceries questions, answered by the experts: https://t.co/RcnZTizHWM via @voxdotcom"
30161,33960,78912,"Washington, DC",06-04-2020,Fed procurement data shows US taxpayers in some cases pay more for R amp D and manufacturing of COVID 19 drugs vaccines than drug makers Some are angry the gov t lets companies set prices even when taxpayers are the majority investor paywall

In [13]:
target = "Sentiment"

# Auto exploration blueprint

In [14]:
twitter = classification_blueprints.ClassificationBluePrint(datasource=train_df, 
                        target_variable=target,
                        train_split_type='cross',
                        nlp_transformer_columns='OriginalTweet',
                        transformer_epochs = 20, # by default this is 20
                        transformer_chosen='bert-base-uncased'
                        #categorical_columns=cat_columns
                                                               )
twitter.ml_bp_06_multiclass_full_processing_bert_transformer()

Ml task is multiclass
Preferred training mode auto has been chosen. e2eml will automatically detect, if LGBM and Xgboost can use GPU acceleration and optimize the workflow accordingly.
Started Execute test train split at 07:06:37.
Started Execute label encoding at 07:06:37.
Started Execute label encoding at 07:06:37.
Started Sort columns alphabetically at 07:06:38.

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                    | 0/20 [00:00<?, ?it/s]

---------------0start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.24326370414013943
valscore is 0.5401131704912565
Save first model

  5%|██                                       | 1/20 [03:12<1:00:59, 192.60s/it]

---------------1start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.6535779204055496

 10%|████▎                                      | 2/20 [06:15<56:08, 187.16s/it]

valscore is 0.7178342059095915
---------------2start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.7978058224541258

 15%|██████▍                                    | 3/20 [09:19<52:33, 185.48s/it]

valscore is 0.7768278883589017
---------------3start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.8798560009636791

 20%|████████▌                                  | 4/20 [12:23<49:18, 184.88s/it]

valscore is 0.7973827103295879
---------------4start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9176078391472772

 25%|██████████▊                                | 5/20 [15:27<46:09, 184.64s/it]

valscore is 0.8007503157643918
---------------5start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9427836458074279

 30%|████████████▉                              | 6/20 [18:30<42:58, 184.21s/it]

valscore is 0.8000990628949909
---------------6start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9527931138087292

 35%|███████████████                            | 7/20 [21:34<39:51, 184.00s/it]

valscore is 0.7859319182055833
---------------7start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9671519596708824

 40%|█████████████████▏                         | 8/20 [24:38<36:47, 183.98s/it]

valscore is 0.7854320142311327
---------------8start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9723914415946855

 45%|███████████████████▎                       | 9/20 [27:42<33:42, 183.90s/it]

valscore is 0.7881238164627481
---------------9start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9783803818880167

 50%|█████████████████████                     | 10/20 [30:46<30:39, 183.95s/it]

valscore is 0.7733209361132414
---------------10start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9840504100577362

 55%|███████████████████████                   | 11/20 [33:50<27:35, 183.95s/it]

valscore is 0.787218437506598
---------------11start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.988660082642249

 60%|█████████████████████████▏                | 12/20 [36:54<24:31, 183.99s/it]

valscore is 0.7765660625713131
---------------12start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.991468666539532

 65%|███████████████████████████▎              | 13/20 [39:58<21:27, 183.95s/it]

valscore is 0.7932075858760145
---------------13start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9923169172585016

 70%|█████████████████████████████▍            | 14/20 [43:02<18:24, 184.05s/it]

valscore is 0.8067123763949576
---------------14start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9961319839352999

 75%|███████████████████████████████▌          | 15/20 [46:05<15:19, 183.86s/it]

valscore is 0.8015050935377748
---------------15start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9948072500910674

 80%|█████████████████████████████████▌        | 16/20 [49:08<12:14, 183.61s/it]

valscore is 0.7989410069345073
---------------16start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9974035944093286

 85%|███████████████████████████████████▋      | 17/20 [52:12<09:10, 183.54s/it]

valscore is 0.7958026733539945
---------------17start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9981454727729128

 90%|█████████████████████████████████████▊    | 18/20 [55:15<06:07, 183.51s/it]

valscore is 0.8065759113651517
---------------18start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9987813077100854

 95%|███████████████████████████████████████▉  | 19/20 [58:19<03:03, 183.49s/it]

valscore is 0.805800976969214
---------------19start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9989402541187801

100%|████████████████████████████████████████| 20/20 [1:01:22<00:00, 184.14s/it]

valscore is 0.8098014949241696
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                    | 0/20 [00:00<?, ?it/s]

---------------0start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.18451955243259
valscore is 0.4860469377295045
Save first model

  5%|██                                       | 1/20 [03:12<1:00:54, 192.33s/it]

---------------1start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.6338939168249692
valscore is 0.7118802200342197
found better point

 10%|████▎                                      | 2/20 [06:24<57:44, 192.45s/it]

---------------2start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.8030568561974251
valscore is 0.7805471925439124
found better point

 15%|██████▍                                    | 3/20 [09:37<54:31, 192.46s/it]

---------------3start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.8828161542879732
valscore is 0.7842773207164319
found better point

 20%|████████▌                                  | 4/20 [12:49<51:18, 192.39s/it]

---------------4start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9122474396611056
valscore is 0.81281377057172
found better point

 25%|██████████▊                                | 5/20 [16:02<48:06, 192.42s/it]

---------------5start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9315923455822108

 30%|████████████▉                              | 6/20 [19:04<44:06, 189.00s/it]

valscore is 0.8019584931729498
---------------6start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9518361485302625

 35%|███████████████                            | 7/20 [22:07<40:32, 187.15s/it]

valscore is 0.8015744970208188
---------------7start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9620046302718053

 40%|█████████████████▏                         | 8/20 [25:12<37:15, 186.26s/it]

valscore is 0.8117679693792261
---------------8start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9706494315143328

 45%|███████████████████▎                       | 9/20 [28:15<33:59, 185.42s/it]

valscore is 0.7989952399246082
---------------9start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9782745322251027

 50%|█████████████████████                     | 10/20 [31:19<30:49, 184.97s/it]

valscore is 0.7834410867932811
---------------10start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9826208146015021

 55%|███████████████████████                   | 11/20 [34:22<27:40, 184.45s/it]

valscore is 0.802129388671655
---------------11start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9870177505080541

 60%|█████████████████████████▏                | 12/20 [37:26<24:33, 184.23s/it]

valscore is 0.7999897243598041
---------------12start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9901440887323231

 65%|███████████████████████████▎              | 13/20 [40:30<21:29, 184.25s/it]

valscore is 0.7944050824508018
---------------13start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9927939597162083
valscore is 0.8160652506431554
found better point

 70%|█████████████████████████████▍            | 14/20 [43:44<18:41, 186.93s/it]

---------------14start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9941714375959109
valscore is 0.8186565905275062
found better point

 75%|███████████████████████████████▌          | 15/20 [46:57<15:43, 188.75s/it]

---------------15start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.995814044551455

 80%|█████████████████████████████████▌        | 16/20 [50:01<12:29, 187.40s/it]

valscore is 0.8163103314936099
---------------16start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9976155591043827

 85%|███████████████████████████████████▋      | 17/20 [53:04<09:18, 186.25s/it]

valscore is 0.8094143375082485
---------------17start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9976685118975228

 90%|█████████████████████████████████████▊    | 18/20 [56:07<06:10, 185.25s/it]

valscore is 0.8142878383629331
---------------18start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9987812968807221

 95%|███████████████████████████████████████▉  | 19/20 [59:10<03:04, 184.56s/it]

valscore is 0.8186462191264666
---------------19start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.998993278721214

100%|████████████████████████████████████████| 20/20 [1:02:13<00:00, 186.70s/it]

valscore is 0.8164688164151884
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                    | 0/20 [00:00<?, ?it/s]

---------------0start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.20896610061046395
valscore is 0.5332469671757006
Save first model

  5%|██                                       | 1/20 [03:11<1:00:36, 191.41s/it]

---------------1start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.6457989655655644
valscore is 0.7268358282860575
found better point

 10%|████▎                                      | 2/20 [06:23<57:37, 192.09s/it]

---------------2start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.8081797046064453
valscore is 0.76966951415607
found better point

 15%|██████▍                                    | 3/20 [09:36<54:30, 192.39s/it]

---------------3start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.8738731082688846
valscore is 0.7921152698527882
found better point

 20%|████████▌                                  | 4/20 [12:49<51:17, 192.36s/it]

---------------4start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.915607550340431
valscore is 0.8132037598617043
found better point

 25%|██████████▊                                | 5/20 [16:02<48:09, 192.62s/it]

---------------5start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9386544434739191

 30%|████████████▉                              | 6/20 [19:05<44:12, 189.50s/it]

valscore is 0.8121744627487223
---------------6start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9486100611862335
valscore is 0.818858146916851
found better point

 35%|███████████████                            | 7/20 [22:18<41:18, 190.65s/it]

---------------7start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9649293149842234

 40%|█████████████████▏                         | 8/20 [25:21<37:39, 188.28s/it]

valscore is 0.8029434234915471
---------------8start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9713404609448058

 45%|███████████████████▎                       | 9/20 [28:24<34:12, 186.61s/it]

valscore is 0.8003030425114679
---------------9start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9782228471613055

 50%|█████████████████████                     | 10/20 [31:28<30:58, 185.82s/it]

valscore is 0.8104277760957195
---------------10start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9807661919912093

 55%|███████████████████████                   | 11/20 [34:32<27:47, 185.31s/it]

valscore is 0.7908681561925471
---------------11start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.986541243439163

 60%|█████████████████████████▏                | 12/20 [37:36<24:38, 184.83s/it]

valscore is 0.8130147883660932
---------------12start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.988130489691193

 65%|███████████████████████████▎              | 13/20 [40:40<21:31, 184.49s/it]

valscore is 0.8108254180188625
---------------13start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9910453498857434

 70%|█████████████████████████████▍            | 14/20 [43:44<18:26, 184.35s/it]

valscore is 0.8073379837967692
---------------14start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9938004249552905

 75%|███████████████████████████████▌          | 15/20 [46:48<15:21, 184.35s/it]

valscore is 0.8012042754789338
---------------15start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9956550994360674

 80%|█████████████████████████████████▌        | 16/20 [49:51<12:15, 183.99s/it]

valscore is 0.8048407508082853
---------------16start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.996343908745706

 85%|███████████████████████████████████▋      | 17/20 [52:55<09:11, 183.95s/it]

valscore is 0.8047522838457425
---------------17start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9981455139193196

 90%|█████████████████████████████████████▊    | 18/20 [55:59<06:07, 183.83s/it]

valscore is 0.8149585665400859
---------------18start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9984103803899412

 95%|███████████████████████████████████████▉  | 19/20 [59:03<03:03, 183.90s/it]

valscore is 0.8164875342423445
---------------19start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9988342901672091

100%|████████████████████████████████████████| 20/20 [1:02:07<00:00, 186.35s/it]

valscore is 0.8160538076069125
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                    | 0/20 [00:00<?, ?it/s]

---------------0start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.18350482646891428
valscore is 0.5189747094056696
Save first model

  5%|██                                       | 1/20 [03:12<1:00:51, 192.19s/it]

---------------1start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.6422970639936765
valscore is 0.718553784472172
found better point

 10%|████▎                                      | 2/20 [06:24<57:43, 192.41s/it]

---------------2start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.7971616610587604
valscore is 0.7245113264590077
found better point

 15%|██████▍                                    | 3/20 [09:37<54:34, 192.62s/it]

---------------3start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.874632139680973
valscore is 0.7905424240845662
found better point

 20%|████████▌                                  | 4/20 [12:49<51:20, 192.52s/it]

---------------4start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9166512571410528

 25%|██████████▊                                | 5/20 [15:53<47:19, 189.33s/it]

valscore is 0.7827435460602769
---------------5start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9425630306938177

 30%|████████████▉                              | 6/20 [18:56<43:41, 187.26s/it]

valscore is 0.7840212430145284
---------------6start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9576630842815185

 35%|███████████████                            | 7/20 [22:00<40:18, 186.07s/it]

valscore is 0.7864507016243916
---------------7start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9649763334191656

 40%|█████████████████▏                         | 8/20 [25:04<37:06, 185.55s/it]

valscore is 0.7898682887662846
---------------8start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9699000298724879
valscore is 0.8063714265353301
found better point

 45%|███████████████████▎                       | 9/20 [28:17<34:24, 187.72s/it]

---------------9start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9820362316283832

 50%|█████████████████████                     | 10/20 [31:20<31:03, 186.35s/it]

valscore is 0.8028526491034309
---------------10start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9860639835547739
valscore is 0.8078555177415534
found better point

 55%|███████████████████████                   | 11/20 [34:33<28:14, 188.30s/it]

---------------11start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.988130371903306

 60%|█████████████████████████▏                | 12/20 [37:36<24:54, 186.80s/it]

valscore is 0.7906749318815987
---------------12start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9897210377074829

 65%|███████████████████████████▎              | 13/20 [40:40<21:41, 185.89s/it]

valscore is 0.798736075753405
---------------13start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9945422673881356

 70%|█████████████████████████████▍            | 14/20 [43:44<18:31, 185.25s/it]

valscore is 0.8034299713292116
---------------14start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9949663617676248

 75%|███████████████████████████████▌          | 15/20 [46:47<15:23, 184.70s/it]

valscore is 0.7924631914522483
---------------15start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9951250645166375

 80%|█████████████████████████████████▌        | 16/20 [49:51<12:17, 184.37s/it]

valscore is 0.8012086258576172
---------------16start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9975626254148433
valscore is 0.8119775442709228
found better point

 85%|███████████████████████████████████▋      | 17/20 [53:03<09:20, 186.80s/it]

---------------17start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9977746303692241

 90%|█████████████████████████████████████▊    | 18/20 [56:07<06:11, 185.78s/it]

valscore is 0.8013146738269933
---------------18start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9989402817224815
valscore is 0.8124974718653366
found better point

 95%|███████████████████████████████████████▉  | 19/20 [59:19<03:07, 187.84s/it]

---------------19start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9989402611941213

100%|████████████████████████████████████████| 20/20 [1:02:24<00:00, 187.21s/it]

valscore is 0.8122208955397998
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                    | 0/20 [00:00<?, ?it/s]

---------------0start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.24363646377396242
valscore is 0.5801084617545307
Save first model

  5%|██                                       | 1/20 [03:13<1:01:07, 193.00s/it]

---------------1start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.6497254926715106
valscore is 0.6751016578828204
found better point

 10%|████▎                                      | 2/20 [06:25<57:49, 192.77s/it]

---------------2start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.799337713526004
valscore is 0.7828353965607916
found better point

 15%|██████▍                                    | 3/20 [09:38<54:41, 193.00s/it]

---------------3start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.8751663956537075
valscore is 0.8126137354490109
found better point

 20%|████████▌                                  | 4/20 [12:51<51:23, 192.71s/it]

---------------4start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9184795475313665

 25%|██████████▊                                | 5/20 [15:54<47:20, 189.35s/it]

valscore is 0.7948421370546801
---------------5start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9386205234945074

 30%|████████████▉                              | 6/20 [18:58<43:43, 187.41s/it]

valscore is 0.7951858862755765
---------------6start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9540734194821172

 35%|███████████████                            | 7/20 [22:01<40:17, 185.99s/it]

valscore is 0.8007193141838401
---------------7start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9589386580278244

 40%|█████████████████▏                         | 8/20 [25:05<37:03, 185.30s/it]

valscore is 0.8064636800436842
---------------8start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9644523776567463
valscore is 0.8182514558642756
found better point

 45%|███████████████████▎                       | 9/20 [28:17<34:24, 187.64s/it]

---------------9start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9774827225960662

 50%|█████████████████████                     | 10/20 [31:21<31:03, 186.31s/it]

valscore is 0.815700970325705
---------------10start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9824611476460263

 55%|███████████████████████                   | 11/20 [34:24<27:49, 185.46s/it]

valscore is 0.8160868163818896
---------------11start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9845280738779727

 60%|█████████████████████████▏                | 12/20 [37:28<24:39, 184.90s/it]

valscore is 0.8103456340601006
---------------12start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9888725265378543

 65%|███████████████████████████▎              | 13/20 [40:33<21:35, 185.03s/it]

valscore is 0.8142537795512801
---------------13start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9917870456765848
valscore is 0.8229044579995289
found better point

 70%|█████████████████████████████▍            | 14/20 [43:46<18:44, 187.41s/it]

---------------14start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.992316787234327

 75%|███████████████████████████████▌          | 15/20 [46:50<15:31, 186.34s/it]

valscore is 0.8139840585518712
---------------15start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9952311483807189
valscore is 0.8233250145399693
found better point

 80%|█████████████████████████████████▌        | 16/20 [50:03<12:33, 188.36s/it]

---------------16start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9972976864818178

 85%|███████████████████████████████████▋      | 17/20 [53:07<09:21, 187.00s/it]

valscore is 0.8154746337435437
---------------17start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9973506605123887

 90%|█████████████████████████████████████▊    | 18/20 [56:11<06:12, 186.13s/it]

valscore is 0.8206657630893509
---------------18start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9979864884144491

 95%|███████████████████████████████████████▉  | 19/20 [59:15<03:05, 185.44s/it]

valscore is 0.817944027502612
---------------19start-------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
trainscore is 0.9988343174565727
valscore is 0.8234972193060229
found better point

100%|████████████████████████████████████████| 20/20 [1:02:28<00:00, 187.43s/it]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model4.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model0.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model3.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model2.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model1.pth']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       23676 non-null  object
 1   OriginalTweet  30000 non-null  object
 2   ScreenName     30000 non-null  int64
 3   TweetAt        30000 non-null  object
 4   UserName       30000 non-null  int64
 5   Sentiment      30000 non-null  int64
 6   kfold          30000 non-null  int64
 7   bins           30000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.8+ MB
None
The Matthew correlation is 0.01611923076816663
-------------------
The accuracy is 0.2265
The macro F1 score is 0.2123446864228664
The micro F1 score is 0.2265
The weighted F1 score is 0.22639442343296062
              precision    recall  f1-score   support

           0       0.19      0.19      0.19      1096
           1       0.29      0.29      0.29      1651
           2       0.26      0.26      0.26      1476
           3       0.16      0.15      0.16       835
           4       0.16      0.16      0.16       942

    accuracy                           0.23      6000
   macro avg       0.21      0.21      0.21      6000
weighted avg       0.23      0.23      0.23      6000

In [15]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   UserName       30000 non-null  int64
 1   ScreenName     30000 non-null  int64
 2   Location       23676 non-null  object
 3   TweetAt        30000 non-null  object
 4   OriginalTweet  30000 non-null  object
 5   Sentiment      30000 non-null  object
dtypes: int64(2), object(4)
memory usage: 1.4+ MB

In [16]:
twitter.df_dict["X_train"]

,Location,OriginalTweet,ScreenName,TweetAt,UserName,Sentiment,kfold
0,Yorkshire and The Humber,Good job I like Rhubarb and Custard Creams 19,62142,21-03-2020,17190,4,1
1,Australia,"ÂIn case they forgot, IÂd like to say thank you to the teachers. YouÂre legends.Â \r\r\nhttps://t.co/c2YqdO7uka",53530,18-03-2020,8578,4,1
2,Canada,Want to know if your local grocery store has stock Or to chat online with folks in your neighbourhood to see how they re doing is a great spot to connect,58558,20-03-2020,13606,4,1
3,NaN,"Looks like the #CoronaVirus will help #Amazon to achive its goal. Amazon to Hire 100,000 new workers due to massive increase in online shopping.\r\r\n\r\r\nhttps://t.co/vbnilTu6xP https://t.co/aSMLBtD2Y2",52679,18-03-2020,7727,4,1
4,"Thame, England","We've updated our online resource of local businesses and services tonight to make it super easy to shop local, support local businesses and find what you are looking for ?\r\r\n\r\r\nhttps://t.co/gw111jI5ec\r\r\n\r\r\n#thame #Haddenham #LongCrendon #chinnor #Covid_19",63126,21-03-2020,18174,4,1
...,...,...,...,...,...,...,...
23995,NaN,"@zoyoudidnt He's a DJ in clubs, I think it's meant more ""I've lost my job because of covid 19, not going to sit at home whilst my wife works saving lives in this crisis"" rather than ""working in a supermarket is shameful""",61042,21-03-2020,16090,3,4
23996,"Tiburon, CA","As the #coronavirus crisis makes the current market volatility worse, @IEA finds we could see even more venting &amp; flaring due to low prices. @EPA must stop attacking #CutMethane safeguards. https://t.co/C2Z2jKDWgi",75520,02-04-2020,30568,3,4
23997,NaN,"Good morning everyone, except you panic buyers. Stop being so greedy and leave some food for others. \r\r\n\r\r\nWith everything going on in the world, this covid 19 is very serious right now. Stay safe, stay blessed and enjoy your days, appreciate some time with your loved ones ?",54838,19-03-2020,9886,4,4
23998,"Grey Highlands, Ontario","For a 45-day period, the government is working to suspend time-of-use electricity rates, holding electricity prices to the off-peak rate of 10.1 cents-per-kilowatt-hour. #OntarioEnergy? https://t.co/wXTjyc8dKg https://t.co/KCy7IZ4jkI",71669,25-03-2020,26717,2,4
23999,Mother Earth,Coronavirus San Jose grocery store temporarily shuts down after employee dies from COVID 19,68173,24-03-2020,23221,0,4

# Test on holdout set

In [17]:
holdout_df

,UserName,ScreenName,Location,TweetAt,OriginalTweet
30157,33956,78908,"Houston, TX",06-04-2020,"Financial markets have not been immune to the #coronavirus fallout, as panic-driven selling along with the uncertainty of our new economic reality combined to send asset prices sharply lower during the first quarter: https://t.co/SeOHvVZzKr\r\r\n\r\r\n#Markets #Investing"
30158,33957,78909,NaN,06-04-2020,The government need to force Argos to close Do they sell food Medicine So why is rhe queue 10x that of the supermarket
30159,33958,78910,NaN,06-04-2020,"3D model of the spread of coronavirus when a person coughs in a supermarket, created by the Aalto University. #Corona #Covid_19 #COVID19 https://t.co/HOzLTAJM1E"
30160,33959,78911,"Washington, DC Metro",06-04-2020,"Your #coronavirus #groceries questions, answered by the experts: https://t.co/RcnZTizHWM via @voxdotcom"
30161,33960,78912,"Washington, DC",06-04-2020,Fed procurement data shows US taxpayers in some cases pay more for R amp D and manufacturing of COVID 19 drugs vaccines than drug makers Some are angry the gov t lets companies set prices even when taxpayers are the majority investor paywall
...,...,...,...,...,...
41152,44951,89903,"Wellington City, New Zealand",14-04-2020,Airline pilots offering to stock supermarket shelves in #NZ lockdown #COVID-19 https://t.co/cz89uA0HNp
41153,44952,89904,NaN,14-04-2020,Response to complaint not provided citing COVID-19 related delays. Yet prompt in rejecting policy before consumer TAT is over. Way to go ?
41154,44953,89905,NaN,14-04-2020,"You know itÂs getting tough when @KameronWilds is rationing toilet paper #coronavirus #toiletpaper @kroger martinsville, help us out!!"
41155,44954,89906,NaN,14-04-2020,Is it wrong that the smell of hand sanitizer is starting to turn me on?\r\r\n\r\r\n#coronavirus #COVID19 #coronavirus
41156,44955,89907,i love you so much || he/him,14-04-2020,@TartiiCat Well new/used Rift S are going for $700.00 on Amazon rn although the normal market price is usually $400.00 . Prices are really crazy right now for vr headsets since HL Alex was announced and it's only been worse with COVID-19. Up to you whethe

In [18]:
len(holdout_target)

11000

In [19]:
twitter.ml_bp_06_multiclass_full_processing_bert_transformer(holdout_df)

Started Execute test train split at 12:18:57.
Started Sort columns alphabetically at 12:18:57.

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model4.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model0.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model3.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model2.pth', '/home/thomas/Schreibtisch/Data Science/Preprocessing lib test/model1.pth']

In [20]:
print(twitter.nlp_transformer_columns)

OriginalTweet

In [23]:
val_df_target = twitter.label_encoder_decoder(holdout_target, mode='transform')
val_df_target

Started Execute label encoding at 12:21:23.

30157    3
30158    0
30159    1
30160    0
30161    2
        ..
41152    0
41153    3
41154    1
41155    0
41156    2
Name: Sentiment, Length: 11000, dtype: int64

In [24]:
from sklearn.metrics import matthews_corrcoef, roc_auc_score, f1_score
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
print(classification_report(val_df_target, val_y_hat))
try:
    matthews = matthews_corrcoef(val_df_target, val_y_hat)
except Exception:
    print("Matthew failed.")
    matthews = 0
print(matthews)

              precision    recall  f1-score   support

           0       0.89      0.90      0.89      2200
           1       0.85      0.88      0.86      3124
           2       0.84      0.85      0.84      2493
           3       0.90      0.84      0.87      1295
           4       0.91      0.89      0.90      1888

    accuracy                           0.87     11000
   macro avg       0.88      0.87      0.87     11000
weighted avg       0.87      0.87      0.87     11000

0.8366325987764442